spring:
  h2.console:
    enabled: true
  datasource:
    url: 'jdbc:h2:file:/F:/spring-todo/todo-list-app/tasks-db'
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'